// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvbhppdsrfoqnpriffmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2YmhwcGRzcmZvcW5wcmlmZm1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzgwNzcsImV4cCI6MjA2MjY1NDA3N30.u-ZpKd-qTYnK6MWgPlzrN1sigx8X0AfVnDPfk8-XYNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storageKey: 'nutrivida-auth-storage',
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});